# ERROR Response
{
  "error": {
    "message": "(#-1) Send API unexpected internal error",
    "type": "OAuthException",
    "code": -1,
    "error_subcode": 2018012,
    "fbtrace_id": "G1lQWWzZaIu"
  }
}
